name: Pattern Analysis

on:
  push:
    paths:
      - 'sessions/*.md'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install numpy pandas matplotlib seaborn
    
    - name: Run Pattern Analysis
      run: |
        python pattern_analyzer.py
    
    - name: Upload Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results/*
        git commit -m "Update pattern analysis results" || exit 0
        git push
